### ISSUE TITLE
index.htmlのファイルが文字化けする

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#1]
videoファイルは大丈夫なのにindex.htmlのファイルだけなぜか文字化けが治らず
ヘッダーに入れた文字も反映されない。
![2019-02-05 20 11 40](https://user-images.githubusercontent.com/22333359/52269768-4dd80200-2982-11e9-9c14-98ad2df4496c.png)
ローカルファイルで確認していた時は問題なかったのですが。

**Comment by happa** [comment]
これはcharsetが指定されていますかね？
```
<meta charset="utf-8">
```
が必要かもしれません。

**Comment by Yumikot** [comment]
あれ、、書いているんですけれど。。一旦書き直してみます。
