### ISSUE TITLE
index.htmlのヘッダーの文字が消えてしまう

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#2]
その他の部分は画面サイズを変更しても表示がされるけれど
ヘッダー部分に入れているh1とpタグの文字が消えてしまう。
メディアクエリの指定とかはしていません。
最初は単純にfontcolorを指定していなかったので（背景が黒なのに黒文字だったからかと思い）fontを白に指定し直してみました。
![2019-02-05 20 46 44](https://user-images.githubusercontent.com/22333359/52271508-30f1fd80-2987-11e9-89b7-d055fe9942c3.png)
サイズを変えると
![2019-02-05 20 46 31](https://user-images.githubusercontent.com/22333359/52271523-3d765600-2987-11e9-9921-a5416f0f3785.png)
```
<!--main start-->
<div class="main">
	<img src="img/back.png" alt="topimage" class="topimage">
　<div class="letter">
	  <h1 class="topline">動画を検索して練習しよう</h1>
	  <p class="lead">ポールダンスのトリックを検索して閲覧、練習してチェックできます</p>
	  <h2>poledanceJiten</h2>
	  <p>Let's get started</p>
	  <a class="btn btn-warning btn-lg" href="#" role="button">create your account</a>
  </div>
</div>
<!--end main-->
```

**Comment by happa** [comment]
ブレークポイントの設定じゃないでしょうかね？
サイズによって幅の指定をすればよいのではと想像します。
以下を参考にしてみてください。

https://skillhub.jp/courses/168/lessons/929
https://qiita.com/tonkotsuboy_com/items/7c01460b59c3ca5ee047

**Comment by happa** [comment]
これはバックグランドに読み込むと良いと思います。画像として貼るのではなく、jumbotronのバックごラウンドに画像を読み込むと良いかと思います。heightなどの指定はせずにしてみてください。

まずは背景に読み込ませることから始めてみてください。

**Comment by Yumikot** [comment]
cssにbackground-imageを指定しているのですが
反映がされていないです。
urlもimg/background.pngでフォルダの指定もつけているんですが。
何か見落としているんでしょうか？
```
.jumbotron-extend{
	background-image: url("img/background.png");
    background-size: cover;
	
}
```
