### ISSUE TITLE
jumbotronを使った場合のcssの変更

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#3]
jumbotronを使った時、普通にcssで色を変更しようとしても変わらないので今の所
htmlに以下のように書いています。
```
<h1 class="text-white">動画を検索して練習しよう</h1>
	  <p class="text-white">ポールダンスのトリックを検索して閲覧、練習してチェックできます</p>
	  <h2 class="text-white">poledanceJiten</h2>
	  <p class="text-white">Let's get started</p>
```
しかし、文字の場所も移動したいし、変更をcssで行いたいのですが
下記のリンクを参考にしながら
クラスの指定をしても.jumbotron-extend h1　など指定してもcssが反映されません。
[https://tonari-it.com/css-customize/](url)
色はまあ、htmlで指定してもいいとして、文字やボタンの位置を変更するのをcssで反映させるのが現状できなくて困っています。

**Comment by happa** [comment]
jumbotron内のテキストカラー（h1）を変更したいのですかね？

**Comment by Yumikot** [comment]
テキストカラーを変更は書き方を変えていけました。とりあえずh1にクラスをつけずにこんな感じのコードを書いて修正して見ました。
```
.jumbotron-extend h1,h2,p{
	color: white;
	text-align: center;
}
```
h1だけクラスをdisplay-4
にして見ました。また引き続き別問題が出たので別のissueに書きます
