### ISSUE TITLE
aタグ問題

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#4]
aタグで囲っているボタンですが
ひとまずレイアウトを変えてみようと思いfloat:rightにしてmargin-rightして無理やり中央寄せにして見たんですが。
その場合、幅を狭めて行くとボタンが枠から出て行ってしまいます。margin-bottomを指定して見たのですけどそれもダメで。
自分の認識ではcontainerの中に入ってるaタグなのでmargin指定したら出ない。と思っていたのですが。
![2019-02-07 18 56 30](https://user-images.githubusercontent.com/22333359/52403493-33c92b80-2b0a-11e9-8be3-0bed73de01a0.png)
そしていずれにせよ幅を狭めて行くとレイアウトが崩れまくるので指定の仕方がそもそも違うのかなと思うのですが。
```
.jumbotron-extend a{
	float: right;
	margin-right: 450px;
	margin-bottom: 30px;
}
```
bottomは適当につけて見ました。

**Comment by happa** [comment]
ボタンはfloat: rightは要らないかなと思います。
これは参考サイトを見て研究すると良いですね。こちらと同じように設定すると良いと思いますので、まずはこちらを真似してみてください。
https://getbootstrap.com/docs/4.2/examples/carousel/
