### ISSUE TITLE
containerに入れている<h2>だけが表示されない

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#5]
display-3などを入れると文字が表示されるのですが設定されてるサイズだと大きすぎるので
h2タグで、、と文字を囲むと文字が消えてしまいます。

```
                <div class="col-md-12">
			<h2>動画でトリックをマスターする</h2>
		</div>
```
![2019-02-08 12 04 11](https://user-images.githubusercontent.com/22333359/52456847-34a99e00-2b9a-11e9-8ec6-31c018d7ced5.png)

しかしh1やh3だと表示されます。

```
                <div class="col-md-12">
			<h3>動画でトリックをマスターする</h3>
		</div>
```

![2019-02-08 12 05 27](https://user-images.githubusercontent.com/22333359/52456794-e0062300-2b99-11e9-9efa-26be9a570fff.png)

ドキュメントをみてもhタグは表示の大きさとか基準のサイズとかは書いていると思うのですが
なぜ、h2だけが表示がなされないのか。
そもそもどこかで例えばcolorをwhiteで指定している？←.jumbotron-extendではh2をwhiteに指定していますですがその指定はしてないので違うと思うのですが。
他の部分では(例えばトップのところなど）h2タグは使えていますし。

**Comment by happa** [comment]
スペースは空いているので、もしかしたら文字色が白になってたりしないですか？

**Comment by Yumikot** [comment]
白でした予想通り。
```
.jumbotron-extend h1,h2,p{
	color: white;
```
のh2につけたのがきいてしまっているってことですね。
クラスをつけているからそのクラスしか適用されないのだと思っていました。
別途h2タグにクラスをつけて、色指定をすると表示ができました！
