### ISSUE TITLE
幅を狭めた際にtrickのカードが上下くっついている見た目

### ISSUE THREAD

**Issue by Yumikot** [Yumikot/poledance_jiten#6]
bootstrapで諸々修正しました。
カードを並べているtrickimages.htmlのページなどで
幅を狭めていったとき、同じdiv class=rowの中にいるカードたちが上下くっついてしまうのですが
これは無くせるのでしょうか？（無くしたほうがいいのでしょうか）
![2019-02-09 12 57 33](https://user-images.githubusercontent.com/22333359/52516246-d4cef800-2c6a-11e9-9b92-8b1fc2f043d9.png)
ちょっときになるような、そうでもないような。でも個人的には上下ぴったりくっついてるのは若干違和感があるのですが。どうでしょうか。
![2019-02-09 13 03 12](https://user-images.githubusercontent.com/22333359/52516264-28d9dc80-2c6b-11e9-98fe-e326e563bc64.png)
これもブレーブレークポイントの指定をしたほうがいいですか？

**Comment by happa** [comment]
そうですね。ちょっと違和感がありますねぇ。上下にmarginを入れてはどうでしょうか？
Bootstrap4ではmarginを入れるのにmt-1とかmt-2とかが使えますので、そちらを使うといいかもしれないですね。

**Comment by Yumikot** [comment]
mt-3を入れて間隔作りました！
![2019-02-09 14 27 01](https://user-images.githubusercontent.com/22333359/52516965-d30b3180-2c76-11e9-9bb7-23f0b7c56131.png)
