### ISSUE TITLE
Globalナビや動画一覧のコンテンツをContainerに入れる

### ISSUE THREAD

**Issue by happa** [Yumikot/poledance_jiten#7]
横に広くなりすぎているので、そこを修正したほうが見栄えが良い。

## Globalナビ
![image](https://user-images.githubusercontent.com/30992/52516734-f46a1e80-2c72-11e9-892f-21d9eab21db6.png)

## 動画一覧
![image](https://user-images.githubusercontent.com/30992/52516717-d3a1c900-2c72-11e9-8479-cc0fec4bbdfb.png)

**Comment by Yumikot** [comment]
containerに入れてみました。
![2019-02-09 14 46 56](https://user-images.githubusercontent.com/22333359/52517135-97259b80-2c79-11e9-964e-bdc8cea4e23a.png)
あとログインボタンもマージンをつけました。
![2019-02-09 14 48 32](https://user-images.githubusercontent.com/22333359/52517145-d3f19280-2c79-11e9-9a14-d50622a31e67.png)
こうしてみるとソーシャルボタンがぎゅっとしすぎに感じますかね。。

**Comment by happa** [comment]
ロゴがちょっと大きすぎる気がしますねぇ。他のサイトのロゴも見て参考にすると良いですよ。
サイトの上部にどのくらいの大きさで、どんなロゴがあるのかを調査してみてください。

で、まいどの事になりますが、好きなロゴを3つくらいピックアップしてください。
それらをかけ合わせてオリジナルを作りましょうか。
